# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='reason',
            field=models.TextField(choices=[('SUBSCRIPTION', 'Subscription'), ('WITHDRAWAL', 'Withdrawal')]),
        ),
    ]
